library(lubridate)
graphsDir<-".\\r\\coursera\\Eploratory Analysis\\Week 1\\Assignment"
setwd(graphsDir)
url<-"https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(url, "Fhousehold_power_consumption.zip")
unzip(zipfile = "Fhousehold_power_consumption.zip")
House_Power_Consumption<-read.table("household_power_consumption.txt", header = TRUE, sep = ";")
House_Power_Consumption$Date<-dmy(House_Power_Consumption$Date)
House_Power_Consumption_Subset<-subset(House_Power_Consumption, Date >= "2007-02-01" & Date <= "2007-02-02")
House_Power_Consumption_Subset$Global_active_power<-as.numeric(paste(House_Power_Consumption_Subset$Global_active_power))
House_Power_Consumption_Subset$DateTime<-with(House_Power_Consumption_Subset, as.POSIXct(paste(Date,Time), format="%Y-%m-%d %H:%M"))
House_Power_Consumption_Subset$Sub_metering_1<-as.numeric(paste(House_Power_Consumption_Subset$Sub_metering_1))
House_Power_Consumption_Subset$Sub_metering_2<-as.numeric(paste(House_Power_Consumption_Subset$Sub_metering_2))
House_Power_Consumption_Subset$Sub_metering_3<-as.numeric(paste(House_Power_Consumption_Subset$Sub_metering_3))
House_Power_Consumption_Subset$Voltage<-as.numeric(paste(House_Power_Consumption_Subset$Voltage))
House_Power_Consumption_Subset$Global_reactive_power<-as.numeric(paste(House_Power_Consumption_Subset$Global_reactive_power))
par(mfrow=c(2,2),mar=c(4,4,2,1))
with(House_Power_Consumption_Subset, plot(DateTime, Global_active_power , type = "l", xlab = "", ylab = "Global Active Power"))
with(House_Power_Consumption_Subset, plot(DateTime, Voltage , type = "l"))
with(House_Power_Consumption_Subset, plot(DateTime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(House_Power_Consumption_Subset, lines(DateTime, Sub_metering_2, type = "l", col = "red"))
with(House_Power_Consumption_Subset, lines(DateTime, Sub_metering_3, type = "l", col = "blue"))
legend("topright", pch = "_", col = c("black", "red", "blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(House_Power_Consumption_Subset, plot(DateTime, Global_reactive_power , type = "l"))
dev.copy(png, file = "plot4.png")
dev.off()